%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-ros2cli
Version:        0.39.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ros2cli package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       python%{python3_pkgversion}-argcomplete
Requires:       python%{python3_pkgversion}-packaging
Requires:       python%{python3_pkgversion}-psutil
Requires:       python3
Requires:       ros-rolling-rclpy
Requires:       ros-rolling-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  python%{python3_pkgversion}-pytest-timeout
BuildRequires:  ros-rolling-ament-copyright
BuildRequires:  ros-rolling-ament-flake8
BuildRequires:  ros-rolling-ament-pep257
BuildRequires:  ros-rolling-ament-xmllint
BuildRequires:  ros-rolling-test-msgs
%endif

%description
Framework for ROS 2 command line tools.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/rolling"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Thu Jun 19 2025 Audrow Nash <audrow@openrobotics.org> - 0.39.1-1
- Autogenerated by Bloom

* Fri Apr 25 2025 Audrow Nash <audrow@openrobotics.org> - 0.39.0-1
- Autogenerated by Bloom

* Sun Feb 02 2025 Audrow Nash <audrow@openrobotics.org> - 0.37.0-1
- Autogenerated by Bloom

* Fri Dec 20 2024 Audrow Nash <audrow@openrobotics.org> - 0.36.1-1
- Autogenerated by Bloom

* Wed Nov 20 2024 Audrow Nash <audrow@openrobotics.org> - 0.36.0-1
- Autogenerated by Bloom

* Thu Oct 03 2024 Audrow Nash <audrow@openrobotics.org> - 0.35.0-1
- Autogenerated by Bloom

* Mon Jul 29 2024 Audrow Nash <audrow@openrobotics.org> - 0.34.1-1
- Autogenerated by Bloom

* Mon Jun 17 2024 Audrow Nash <audrow@openrobotics.org> - 0.34.0-1
- Autogenerated by Bloom

* Fri Apr 26 2024 Audrow Nash <audrow@openrobotics.org> - 0.33.0-1
- Autogenerated by Bloom

* Tue Apr 16 2024 Audrow Nash <audrow@openrobotics.org> - 0.32.0-1
- Autogenerated by Bloom

* Thu Mar 28 2024 Audrow Nash <audrow@openrobotics.org> - 0.31.2-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Audrow Nash <audrow@openrobotics.org> - 0.31.1-2
- Autogenerated by Bloom

